### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by blaxer** [go-vikunja/app#102]
I am not able to login using the app v0.1.8 to https://try.vinkunja.io nor my self-hosted docker instance. I have tried using the login button and the login using front-end neither work.  I have tried checking the ignore certificate it did not help. I am using LineageOS with **ZERO** google services installed. In logcat I am getting the following:

12-20 11:40:19.063  2031  2086 W GooglePlayServicesUtil: io.vikunja.app requires the Google Play Store, but it is missing.
12-20 11:40:19.063  2031  2086 E GooglePlayServicesUtil: GooglePlayServices not available due to error 9
12-20 11:40:19.063  2031  2086 I PlayServicesCronet: Google-Play-Services-Cronet-Provider is unavailable.
12-20 11:40:19.064  2031  2086 I flutter : Exception in Java code called through JNI: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
12-20 11:40:19.064  2031  2086 I flutter : 
12-20 11:40:19.064  2031  2086 I flutter : java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
12-20 11:40:19.064  2031  2086 I flutter :      at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(CronetEngine.java:52)
12-20 11:40:19.064  2031  2086 I flutter :      at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(CronetEngine.java:10)
12-20 11:40:19.064  2031  2086 I flutter :      at org.chromium.net.CronetEngine$Builder.<init>(CronetEngine.java:1)

**Comment by kolaente** [comment]
I'm unable to reproduce this with the demo. Vikunja doesn't use any Google services explicitly, so that should not be a problem.

Do you see anything in the Vikunja server logs when attempting to log in?

Which android version are you using?

**Comment by blaxer** [comment]
I do not see any errors in the server logs, just a POST for login and a bunch of GETS all with status 200 coming from the ip of my phone.

I am using Lineage 21 (Android 14). 

If I try "login with frontend" I seem to login fine but immediately get kicked back to the initial Vikunja app login screen. 

I looked at logcat again using verbose and other than the "GooglePlayServicesUtil: io.vikunja.app requires the Google Play Store, but it is missing." I do not see anything else that looks like an error message or something failing.

Other than this issue with the mobile app Vikunja is functioning flawlessly, no issues logging in at all from a browser. I am using nginxproxymanager with a let's encrypt cert which also seems to be working fine.

Not sure where else to look.

**Comment by ratzuballtuf** [comment]
Hi there,
I encountered the same problem with a similar setup: Lineage OS 22.1 (Android 15) with zero google services; device Shift 6mq. Only difference is, I used https://app.vikunja.cloud to log in.
I tried reinstalling the app

Here are my logs from logging in via the mask of the app:
```
01-18 10:07:42.869 13683 13702 W GooglePlayServicesUtil: io.vikunja.app requires the Google Play Store, but it is missing.
01-18 10:07:42.869 13683 13702 E GooglePlayServicesUtil: GooglePlayServices not available due to error 9
01-18 10:07:42.869 13683 13702 I PlayServicesCronet: Google-Play-Services-Cronet-Provider is unavailable.
01-18 10:07:42.869 13683 13702 I flutter : Exception in Java code called through JNI: java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
01-18 10:07:42.869 13683 13702 I flutter :
01-18 10:07:42.869 13683 13702 I flutter : java.lang.RuntimeException: All available Cronet providers are disabled. A provider should be enabled before it can be used.
01-18 10:07:42.869 13683 13702 I flutter :      at org.chromium.net.CronetEngine$Builder.getEnabledCronetProviders(CronetEngine.java:52)
01-18 10:07:42.869 13683 13702 I flutter :      at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(CronetEngine.java:10)
01-18 10:07:42.869 13683 13702 I flutter :      at org.chromium.net.CronetEngine$Builder.<init>(CronetEngine.java:1)
01-18 10:07:42.869 13683 13702 I flutter :
```

Log from logging in via "Login with Frontend"
```
01-18 10:08:28.120 13683 13683 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
01-18 10:08:28.120 13683 13683 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
01-18 10:08:28.240 13683 13683 I chromium: [INFO:CONSOLE(1)] "Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.", source:  (1)
01-18 10:08:28.689 13683 13683 I chromium: [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.", source:  (0)
01-18 10:08:29.042 13683 13683 I chromium: [INFO:CONSOLE(666)] "App is being served from cache by a service worker.", source: https://app.vikunja.cloud/assets/index-BAg_IiNJ.js (666)
01-18 10:08:29.043 13683 13683 I chromium: [INFO:CONSOLE(666)] "Service worker has been registered.", source: https://app.vikunja.cloud/assets/index-BAg_IiNJ.js (666)
01-18 10:08:29.326 13683 13683 I chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: n.vueRouterInstrumentation is not a function", source: https://app.vikunja.cloud/assets/sentry-CMOuGR6_.js (1)
01-18 10:08:35.831 13683 13683 I chromium: [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.", source:  (0)
01-18 10:08:36.056 13683 13683 I chromium: [INFO:CONSOLE(666)] "App is being served from cache by a service worker.", source: https://app.vikunja.cloud/assets/index-BAg_IiNJ.js (666)
01-18 10:08:36.058 13683 13683 I chromium: [INFO:CONSOLE(666)] "Service worker has been registered.", source: https://app.vikunja.cloud/assets/index-BAg_IiNJ.js (666)
01-18 10:08:36.209 13683 13683 I chromium: [INFO:CONSOLE(1)] "Uncaught (in promise) TypeError: n.vueRouterInstrumentation is not a function", source: https://app.vikunja.cloud/assets/sentry-CMOuGR6_.js (1)
01-18 10:08:36.950 13683 13702 I flutter : pop now
01-18 10:08:36.951 13683 13702 W GooglePlayServicesUtil: io.vikunja.app requires the Google Play Store, but it is missing.
01-18 10:08:36.951 13683 13702 E GooglePlayServicesUtil: GooglePlayServices not available due to error 9
01-18 10:08:36.951 13683 13702 I PlayServicesCronet: Google-Play-Services-Cronet-Provider is unavailable.
```

Thanks for looking into this, I hope this can help.

**Comment by Blunderor** [comment]
I found the (implicit) dependency on Google Play Services:
The project [depends on the flutter package "cronet_http"](https://github.com/go-vikunja/app/blob/4a50f7da90db40f8a4b93bce196982b8bbe582de/pubspec.yaml#L46), which in turn [depends on the Google Play Services](https://pub.dev/packages/cronet_http).

I see two options, how this could be solved.

### Option 1: Embedded Cronet

cronet_http mentions a way to use an embedded Cronet implementation instead of the one provided by Google Play Services. However, this would have the [drawback of an increased app size](https://medium.com/@yogigupta1206/implementing-cronet-http3-quic-a55f71cb4bcb).

### Option 2: Cronet Fallback

I found [information here](https://github.com/GoogleChromeLabs/cronet-sample/issues/24#issuecomment-1717326008) about the possibility to fall back to a "less performant implementation of Cronet's API".

I don't know how to implement either of these options, though. Please help, or else this app will not be usable by any Google-free Android phone.

**Comment by SIMULATAN** [comment]
fwiw, this issue is reproducible using the [waydroid emulator](https://waydro.id/), which also uses LineageOS.

**Comment by chriswin23** [comment]
I am encountering the same issue running GrapheneOs. I am also not using any google services. I do not see any errors in the logs, though.

**Comment by leschbenedikt** [comment]
This is resolved in the current beta build

**Comment by chriswin23** [comment]
I have just tested with one of the latest app bundle, and it worked! Thank you very much 🙏
